#!/usr/bin/env httpx --httpfile

### get my internet ip
# @name myip
GET https://httpbin.org/ip

### inspection http post
# @name post
POST https://httpbin.org/post
Content-Type: application/json

[
  1
]

### inspection http get
//@name get
GET https://httpbin.org/get?
  id=123
  &value=content

### RSocket Request
// @name request
RSOCKET com.example.UserService.findById
Host: 127.0.0.1:42252
Content-Type: application/json

1

### RSocket Stream
//@name stream
STREAM com.example.UserService.findAll
Host: 127.0.0.1:42252
Content-Type: application/json

### query by json
//@name query_by_json
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{ films { title releaseYear}}"
}

### graphql query
//@name query
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query {
  bookById(id: "book-1") {
    id
    name
    pageCount
    author {
      firstName
      lastName
    }
  }
}
