#!/usr/bin/env httpx --httpfile

### get my internet ip
# @name myip
GET https://httpbin.org/ip

>>! myip.json

### inspection http post
# @name post
POST https://httpbin.org/post
Content-Type: application/json

[
  1
]

### RSocket Request
// @name request
RSOCKET com.example.UserService.findById
Host: 127.0.0.1:42252
Content-Type: application/json

1

### grpc call SayHello
//@name SayHello
GRPC localhost:50052/Greeter/SayHello

{
  "name": "Jackie"
}

### graphql query over WebSocket
//@name subscription
GRAPHQL ws://localhost:4000/graphql
Content-Type: application/graphql

subscription { greetings }

### Dubbo sayHi
//@name dubbo-hi
DUBBO 127.0.0.1:20880/GreetingsService/sayHi(java.lang.String)
Content-Type: application/json

"jackie"

### sofa findById
//@name sofa-byid
SOFA 127.0.0.1:12200/org.mvnsearch.HelloService/findById(java.lang.Integer)
Content-Type: application/json

1

### send kafka message
//@name kafka-pub
PUB testTopic
Host: kafka://localhost:9092
Content-Type: application/json

{
  "name": "Jackie"
}

###  kafka message
//@name kafka-sub
SUB testTopic
Host: kafka://localhost:9092

### send Nats message
//@name nats
PUB subject1
Host: nats://localhost:4222
Content-Type: application/json

{
  "name": "Jackie"
}

### listen Nats message
//@name nats-sub
SUB subject1
Host: nats://localhost:4222

### publish rabbitmq message
//@name rabbitmq-pub
PUB queue3
Host: amqp://localhost:5672
Content-Type: application/json

{
  "name": "Jackie"
}

### listen rabit message
//@name rabbitmq-sub
SUB queue3
Host: amqp://localhost:5672

### publish redis message
//@name redis-pub
PUB channel1
Host: redis://localhost:6379
Content-Type: application/json

{
  "name": "Jackie"
}

### subscribe redis
//@name redis-sub
SUB channel1
Host: redis://localhost:6379

### publish mqtt message
//@name mqtt-pub
PUB topic1
Host: mqtt://localhost:1883
Content-Type: application/json

{
  "name": "Jackie"
}

### subscribe mqtt
//@name mqtt-sub
SUB topic1
Host: mqtt://localhost:1883

### send stomp message
//@name stomp-pub
PUB queue3
Host: stomp://localhost:61613
Content-Type: application/json

{
  "name": "Jackie"
}

### subscribe stomp
//@name stomp-sub
SUB queue3
Host: stomp://localhost:61613

### publish rocketmq message
//@name rocketmq-pub
PUB testTopic
Host: rocketmq://localhost:9876
Content-Type: application/json

{
  "name": "Jackie"
}

### send pulsar message
//@name pulsar-pub
PUB test-topic
Host: pulsar://localhost:6650
Content-Type: application/json

{
  "name": "Jackie"
}

### subscribe pulsar
//@name pulsar-sub
SUB test-topic
Host: pulsar://localhost:6650

### zeromq request
//@name zero-req
ZEROREQ 127.0.0.1:5555
Content-Type: application/json

"Jackie"

### subscribe zeromq
//@name zero-sub
SUB topic1
Host: zeromq://localhost:5555

### memcache set
//@name mem-set
MEMCACHE user.1
URI: memcache://localhost:11211
Content-Type: application/json

{
  "id": 111,
  "name": "jackie"
}

### memcache set
//@name mem-get
MEMCACHE user.1
URI: memcache://localhost:11211

### redis set
//@name redis-set
RSET nick
Host: localhost:6379
Content-Type: text/plain

Jackie

### redis hmset
//@name redis-hmset
HMSET user.1
Host: localhost:6379
Content-Type: application/json

{
  "id": 1,
  "name": "jackie",
  age: 20
}

### redis Lua eval
//@name redis-eval
EVAL 1 keyname1 value1
Host: localhost:6379

local welcome = "Hello "
return welcome .. KEYS[1]

### redis 7 fuctions
//@name redis-mylib
LOAD mylib
Host: localhost:16379
Content-Type: text/x-lua

#!lua name=mylib
redis.register_function(
        'knockknock',
        function()
            return 'Who\'s there?'
        end
)


### ssh demo
//@name ssh-demo
SSH test:test@localhost:2022

ls -al

### msgpack request
//@name msgpack-rpc
MSGPACK 127.0.0.1:18800/add
Content-Type: application/json

[
  1,
  2
]

### neovim request
//@name nvim-ls
NVIM nvim_exec_lua
Content-Type: text/x-lua

vim.api.nvim_command('!ls')