#!/usr/bin/env httpx --httpfile

### get my internet ip
# @name myip
GET {{base-url}}/ip

>>! myip.json

### inspection http post
# @name post
POST https://httpbin.org/post
Content-Type: application/json

[1]

### RSocket Request
// @name request
RSOCKET com.example.UserService.findById
Host: 127.0.0.1:42252
Content-Type: application/json

1

### grpc call SayHello
//@name SayHello
GRPC localhost:50052/Greeter/SayHello

{
  "name": "Jackie"
}

### graphql query over WebSocket
//@name subscription
GRAPHQL ws://localhost:4000/graphql
Content-Type: application/graphql

subscription { greetings }

### Dubbo sayHi
//@name sayHi
DUBBO 127.0.0.1:20880/GreetingsService?method=sayHi(java.lang.String)
Content-Type: application/json

"jackie"