#!/usr/bin/env httpx --httpfile

### get my internet ip
# @name myip
GET https://httpbin.org/ip

>>! myip.json

### inspection http post
# @name post
POST https://httpbin.org/post
Content-Type: application/json

[1]

### RSocket Request
// @name request
RSOCKET com.example.UserService.findById
Host: 127.0.0.1:42252
Content-Type: application/json

1

### grpc call SayHello
//@name SayHello
GRPC localhost:50052/Greeter/SayHello

{
  "name": "Jackie"
}

### graphql query over WebSocket
//@name subscription
GRAPHQL ws://localhost:4000/graphql
Content-Type: application/graphql

subscription { greetings }

### Dubbo sayHi
//@name sayHi
DUBBO 127.0.0.1:20880/GreetingsService/sayHi(java.lang.String)
Content-Type: application/json

"jackie"

### send kafka message
//@name kafka
PUB topic-1
Host: kafka://localhost:9092
Content-Type: application/json

{
  "name": "Jackie"
}

### send Nats message
//@name nats
PUB subject1
Host: nats://localhost:4222
Content-Type: application/json

{
  "name": "Jackie"
}

### listen Nats message
//@name nats-sub
SUB subject1
Host: nats://localhost:4222

### publish rabit message
//@name rabbit-pub
PUB queue3
Host: amqp://localhost:5672
Content-Type: application/json

{
  "name": "Jackie"
}

### listen rabit message
//@name rabbit-sub
SUB queue3
Host: amqp://localhost:5672